name: "Ensure your library's interface stability"
description: ""

inputs:
  package-name:
    description: "The package to test. Currently only one per project is supported"
    required: true
  package-database:
    description: "The path to the package database, usually located within the store. eg: ~/.cabal/store/ghc-9.6.6/package.db"
    required: true
  expected-interface:
    description: "The file of the expected interface of the package. Generate it yourself with `dump-decls`."
    required: true
  ghc: 
    description: "The version of GHC used to compile the project. See the project's README to know which versions are supported."
    required: true
  version:
    description: "Version of the tool"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout base repo
      uses: actions/checkout@v4
    - name: Set up the binary
      shell: bash
      run: |
        wget -q https://github.com/Kleidukos/dump-decls/releases/download/v${{ inputs.version }}/get-tested-${{ inputs.version }}-linux-amd64 -O dump-decls
        chmod +x dump-decls

    - name: Register the library in the package database
      shell: bash
      run: |
          cabal install -j ${{ inputs.package-name }}
    - name: Dump the actual version
      shell: bash
      run: |
        ./dump-decls --package-name ${{ inputs.package-name }} --package-db=${{ inputs.package-database }} > actual-interface.txt
    - name: Perform the diff between the two versions
      shell: bash
      run: |
        diff ${{ inputs.expected-interface }} actual-interface.txt
          

branding:
  icon: 'list'
  color: 'blue'
