name: Test Reports
on:
  workflow_run:
    workflows: [ "Tests Pipeline" ]
    types: [ completed ]

permissions:
  checks: write

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Install juitparser
        run: |
          pip install junitparser==3.2.0
      - name: Download Test Report
        uses: actions/download-artifact@v4
        with:
          pattern: report-*
          merge-multiple: true
          workflow: ${{ github.event.workflow.id }}
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GH_PAT }} # token with actions:read permissions on target repo
      - name: Merge XML files
        run: |
          junitparser merge --glob *.xml final-report.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        with:
          commit: ${{github.event.workflow_run.head_sha}}
          report_paths: 'final-report.xml'
